import React, { useState, useEffect } from 'react';
import { recommendationsApi } from '../api/api';
import { 
  AlertTriangle, 
  Info, 
  TrendingUp, 
  UserCheck, 
  Users, 
  CheckCircle, 
  AlertCircle,
  Zap
} from 'lucide-react';
import '../styles/RecommendationPage.css';

const RecommendationPage = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        setLoading(true);
        const data = await recommendationsApi.getAll();
        setRecommendations(data || []);
        setError(null);
      } catch (err) {
        console.error("Failed to fetch recommendations:", err);
        setError("Unable to generate recommendations. Please ensure you have enrollment data.");
      } finally {
        setLoading(false);
      }
    };

    fetchRecommendations();
  }, []);

  const getIcon = (category, type) => {
    if (type === 'danger') return <AlertCircle size={24} />;
    
    switch (category) {
      case 'Capacity': return <Users size={24} />;
      case 'Trend': return <TrendingUp size={24} />;
      case 'Retention': return <UserCheck size={24} />;
      case 'Demographics': return <Users size={24} />;
      case 'System': return <CheckCircle size={24} />;
      default: return <Info size={24} />;
    }
  };

  const renderDataTags = (data) => {
    if (!data) return null;
    return Object.entries(data).map(([key, value]) => {
      // Format keys: ratio -> Ratio, changePercent -> Change
      const label = key
        .replace(/([A-Z])/g, ' $1')
        .replace(/^./, str => str.toUpperCase());
      
      const displayValue = typeof value === 'number' && !Number.isInteger(value) 
        ? value.toFixed(1) 
        : value;

      return (
        <span key={key} className="data-tag">
          {label}: {displayValue}{key.toLowerCase().includes('percent') || key.toLowerCase().includes('rate') ? '%' : ''}
        </span>
      );
    });
  };

  if (loading) {
    return (
      <div className="loading-container">
        <div className="spinner"></div>
        <p>Analyzing Live Database...</p>
      </div>
    );
  }

  return (
    <div className="recommendation-container">
      <header className="recommendation-header">
        <h1>Intelligent Insights</h1>
        <p>Data-driven recommendations generated by analyzing your current enrollment and classroom capacity.</p>
      </header>

      {error ? (
        <div className="rec-card danger" style={{ borderLeft: 'none', textAlign: 'center' }}>
          <div className="rec-icon-wrapper" style={{ margin: '0 auto 16px' }}>
            <AlertTriangle size={32} />
          </div>
          <div className="rec-title">Analysis Error</div>
          <p className="rec-message">{error}</p>
        </div>
      ) : recommendations.length === 0 ? (
        <div className="empty-state">
          <Zap size={48} color="#3b82f6" style={{ marginBottom: '16px' }} />
          <h2>Everything looks great!</h2>
          <p>No issues were detected in your current data distribution.</p>
        </div>
      ) : (
        <div className="rec-grid">
          {recommendations.map((rec) => (
            <div key={rec.id} className={`rec-card ${rec.type}`}>
              <div className="rec-icon-wrapper">
                {getIcon(rec.category, rec.type)}
              </div>
              
              <div className="rec-category">{rec.category}</div>
              <h3 className="rec-title">{rec.title}</h3>
              <p className="rec-message">{rec.message}</p>
              
              <div className="rec-footer">
                <div className="rec-data-summary">
                  {renderDataTags(rec.data)}
                </div>
                <div className="rec-action-badge">{rec.action}</div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default RecommendationPage;
